version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: iluvdb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
